
// Sample responses for different career question categories
export const sampleResponses: Record<string, string[]> = {
  interviews: [
    "When preparing for interviews, conduct thorough company research by reviewing their annual reports, recent press releases, and social media presence. According to 'Be Your Own Commander-in-Chief', you should understand their business model, revenue streams, and current challenges. Pay special attention to how your skills align with their strategic objectives.\n\nBefore your interview, prepare specific examples of how you've solved similar problems they might be facing. For technical roles, review their tech stack and prepare to discuss relevant project experience. For leadership roles, have examples of team management and strategic decision-making ready.",
    
    "The STAR method (Situation, Task, Action, Result) is essential for behavioral interviews, but take it further by adding an L for Learning. In the STAR-L approach, conclude each answer with what you learned and how it changed your approach moving forward. This demonstrates growth mindset and self-awareness.\n\nAccording to interview data from top employers, candidates who provide detailed metrics and quantifiable results in their STAR stories are 62% more likely to receive offers. Be specific about the scale of your contributions: team size, budget managed, percentage improvements achieved, and time saved.",
    
    "When asking questions to the interviewer, move beyond generic inquiries. Research suggests that questions demonstrating you've studied the company's recent initiatives create a more favorable impression. Examples include: 'I noticed your company recently launched X initiative. How does this role contribute to that strategic goal?' or 'Your CEO mentioned Y challenge in her recent industry talk. How is your team approaching this problem?'\n\nAlso, ask about the interviewer's personal experience: 'What has been your most rewarding project here?' This builds rapport while gaining insider perspective.",
    
    "Follow-up emails should be personalized and reference specific conversation points from the interview. According to 'Be Your Own Commander-in-Chief', effective follow-ups include: 1) A specific thank you for something you learned, 2) A brief reinforcement of your key qualifications, 3) An additional thought or resource related to a topic discussed, and 4) A clear expression of continued interest.\n\nTiming matters - data shows emails sent within 4-24 hours have the highest response rates. Too quickly might seem prepared in advance; too late suggests lack of interest."
  ],
  salary: [
    "Before salary negotiations, compile comprehensive market data from multiple sources. Beyond Glassdoor and PayScale, incorporate data from Levels.fyi, Blind, the Bureau of Labor Statistics, industry association reports, and company-specific insights from sites like Comparably. Create a detailed comparison table based on your years of experience, location, education, specialized skills, and industry certifications.\n\nAccording to 'Be Your Own Commander-in-Chief', you should calculate your 'personal market value premium' by quantifying your unique contributions: revenue generation potential, specialized expertise, or rare skill combinations. This gives you a precise range with evidence-based justification for your target number.",
    
    "When evaluating compensation packages, create a comprehensive worksheet that monetizes all benefits and perks. The total value often represents 20-40% above base salary. Calculate the actual dollar value of: health insurance (compare to marketplace alternatives), retirement contributions (with projected growth), stock options/RSUs (with projected vesting value), bonuses (probability-adjusted), professional development allowances, and quality of life benefits like remote work flexibility (calculate commute cost/time savings).\n\nResearch shows candidates who properly value the complete package are more successful in negotiations, often securing 12-18% higher total compensation than those focusing solely on base salary.",
    
    "Salary negotiation research from Columbia Business School reveals that using precise numbers signals that you've done detailed research. Instead of requesting $85,000, ask for $87,650. This specificity suggests a carefully calculated valuation based on your market research and personal value proposition. According to 'Be Your Own Commander-in-Chief', you should also prepare a tiered negotiation strategy with your ideal number, target number, and walk-away threshold.\n\nAdditionally, frame your request in terms of the company's benefit: 'Based on the value I'll bring by implementing efficiency systems that saved my previous employer $120,000 annually, I'm seeking $87,650, which represents a strong ROI for the company.'",
    
    "To justify premium compensation, develop a detailed 'Value Creation Plan' that outlines specific contributions you'll make within 30, 60, and 90 days. Quantify potential revenue increases, cost savings, or efficiency improvements with concrete metrics. According to hiring research, candidates who present such plans during negotiations are 37% more likely to secure higher offers.\n\nAlso, compile a portfolio of accomplishment stories with measurable outcomes from previous roles. From 'Be Your Own Commander-in-Chief': 'When you demonstrate that you consistently deliver 1.5-2x the value of average performers, you create a strong case for compensation in the upper quartile of the market range.'"
  ],
  promotion: [
    "To prepare for promotion, document your value creation using the 'Career Capital Framework' from 'Be Your Own Commander-in-Chief'. This involves creating a comprehensive portfolio of: 1) Revenue Impact - direct and indirect contributions to company bottom line, 2) Innovation Capital - process improvements and new initiatives you've led, 3) Expertise Development - specialized knowledge and certifications you've acquired, 4) Leadership Influence - team outcomes and mentoring successes, and 5) Stakeholder Testimonials - documented praise from clients, colleagues and leadership.\n\nStudies of successful promotions show that individuals who systematically document achievements with specific metrics and stakeholder impact are promoted 14-18 months faster than equally qualified peers who don't maintain such records.",
    
    "Strategic visibility requires deliberately choosing high-impact projects. Create a 'project selection matrix' that evaluates potential assignments based on: executive visibility, cross-functional exposure, skills development, measurable outcomes, and strategic alignment with company priorities. Research from 'Be Your Own Commander-in-Chief' suggests that employees who take on projects with high organizational visibility are promoted 1.7x faster than those who focus solely on technical excellence without strategic alignment.\n\nAdditionally, showcase your work effectively through: regular progress updates to leadership, volunteering to present results in company forums, creating documentation of your methodologies, and mentoring others in your approaches.",
    
    "Cultivate a strategic network of mentors, sponsors, and allies using the 'career coalition' approach detailed in 'Be Your Own Commander-in-Chief'. This involves identifying 5-7 key individuals who serve different roles: 1) Technical Mentors who deepen your expertise, 2) Strategic Advisors who understand organizational priorities, 3) Executive Sponsors who advocate for you in leadership discussions, 4) Peer Allies who collaborate on high-visibility initiatives, and 5) External Advisors who provide industry perspective.\n\nResearch from Korn Ferry shows that professionals with structured mentoring relationships are promoted 5x more often than those without such support. Develop a relationship management system with regular check-ins, value exchanges, and strategic updates with each person in your coalition.",
    
    "When requesting a promotion conversation, come prepared with a comprehensive 'Promotion Justification Packet' containing: 1) Detailed documentation of achievements with quantified results, 2) A skills-gap analysis showing how you're already performing at the next level, 3) Market data for the position you're targeting, 4) A role expansion proposal detailing additional responsibilities you'll take on, and 5) A 90-day plan for your transition.\n\nAccording to 'Be Your Own Commander-in-Chief', timing is crucial - schedule these conversations shortly after significant achievements, during annual planning cycles, or when new opportunities emerge in the organization. Research shows that promotion requests that align with business planning cycles have a 40% higher success rate."
  ],
  skills: [
    "Develop T-shaped skills by mapping your expertise using the 'Skill Development Portfolio' approach from 'Be Your Own Commander-in-Chief'. This framework involves: 1) Identifying your deep vertical expertise (the stem of the T), 2) Mapping complementary horizontal skills that enhance your core expertise, 3) Benchmarking your proficiency levels against industry standards, and 4) Creating a deliberate development roadmap.\n\nStudies of high-performers across industries show that the most valuable professionals combine depth in a technical specialty with breadth in applicable business skills like strategic thinking, project management, stakeholder communication, and financial acumen. Those with documented skill development plans advance 31% faster than those with similar capabilities but no structured approach.",
    
    "Conduct a comprehensive skills gap analysis by comparing your current capabilities against: 1) Job descriptions for your target role across multiple companies, 2) LinkedIn profiles of successful professionals in your desired position, 3) Industry certification requirements, and 4) Emerging technology trends in your field. Prioritize skill acquisition based on frequency of mention in job postings, emphasis in performance reviews, and growth trajectory in market demand.\n\nAccording to 'Be Your Own Commander-in-Chief', create a detailed learning roadmap with specific outcomes, resources, practice opportunities, and demonstration projects for each priority skill. Research shows deliberate practice with accountability measures leads to 3-4x faster skill acquisition than unstructured learning.",
    
    "Apply the 'Skill Mastery Framework' from 'Be Your Own Commander-in-Chief' by creating implementation projects for each new skill. This four-stage approach includes: 1) Theoretical Understanding through courses and reading, 2) Guided Application with mentor feedback, 3) Real-World Implementation on actual projects, and 4) Teaching Others to cement mastery.\n\nResearch on learning retention shows that practical application increases skill retention by 65-70% compared to theoretical knowledge alone. For technical skills, contribute to open-source projects; for leadership skills, volunteer for cross-functional initiatives; for analytical skills, offer to solve data challenges in your organization.",
    
    "Select high-ROI certifications by evaluating them against the 'Credential Value Matrix' outlined in 'Be Your Own Commander-in-Chief': 1) Industry Recognition - prevalence in job postings and LinkedIn profiles of senior roles, 2) Skill Validation - rigor of assessment process, 3) Network Access - community and connections granted, and 4) Knowledge Relevance - practical applicability to your target roles.\n\nData shows that the highest-value credentials combine technical validation with practical application. Rather than accumulating numerous certifications, focus on fewer, more prestigious credentials with comprehensive projects that demonstrate real-world application. According to industry studies, professionals with 2-3 premium certifications plus implementation portfolios command higher salary premiums than those with numerous basic credentials."
  ],
  networking: [
    "Build a strategic network using the 'Relationship Portfolio' approach from 'Be Your Own Commander-in-Chief'. This involves categorizing professional relationships into: 1) Strategic Connections - industry leaders and decision-makers, 2) Knowledge Resources - subject matter experts, 3) Opportunity Channels - recruiters and connectors, 4) Support System - mentors and advisors, and 5) Rising Talent - emerging leaders. Research shows diverse networks across these categories correlate with faster career advancement and greater resilience during industry changes.\n\nUse relationship management software or a structured spreadsheet to track key contacts, conversation notes, areas of expertise, assistance provided, and follow-up schedules. According to network science research, maintaining 150-200 active professional relationships with systematic engagement patterns significantly increases career opportunities and knowledge access.",
    
    "Implement the 'Give First Matrix' from 'Be Your Own Commander-in-Chief' by identifying specific value you can provide to each relationship category. This includes: 1) Information sharing (research, articles, trend analysis), 2) Connection brokering (introducing relevant contacts), 3) Visibility creation (highlighting others' work, testimonials), 4) Skill contribution (offering your expertise), and 5) Opportunity alerting (sharing relevant openings or projects).\n\nResearch from Adam Grant's 'Give and Take' confirms that strategic givers who contribute specific value aligned with their expertise build stronger networks than general networkers or those primarily seeking benefits. The key is establishing a reputation as a valuable resource in your specific domain, creating a flywheel effect of reciprocal opportunity.",
    
    "Structure your networking activities using the '5-3-1 Connection System' outlined in 'Be Your Own Commander-in-Chief': 5 new connection requests weekly, 3 relationship-deepening conversations, and 1 strategic networking event. Research shows consistent, moderate-volume networking outperforms sporadic high-intensity efforts.\n\nDiverse engagement channels matter - create a balanced mix of: 1) Industry events for broad exposure, 2) Specialized professional groups for depth, 3) Online communities for geographic reach, 4) Volunteer leadership roles for sustained interaction, and 5) Content creation for passive network building. According to LinkedIn data, professionals who engage across multiple channels build networks that grow 3-4x faster than single-channel networkers.",
    
    "Maintain relationships systematically using the 'Network Nurturing Calendar' approach from 'Be Your Own Commander-in-Chief'. This involves: 1) Tiering your contacts by relationship importance and engagement frequency, 2) Creating a scheduled outreach system with appropriate cadences (A-tier: monthly, B-tier: quarterly, C-tier: biannually), 3) Documenting key personal and professional details for personalized follow-ups, and 4) Tracking reciprocity to ensure mutual value exchange.\n\nUtilize trigger events (promotions, company news, industry developments, shared interests) as natural opportunities for meaningful engagement rather than generic check-ins. Research shows context-specific outreach receives 3x higher response rates than general reconnection attempts. According to network science studies, relationships require 'maintenance interactions' at least quarterly to remain active in your network's conscious awareness."
  ],
  career_change: [
    "Before making a career change, conduct comprehensive informational interviews using the 'Career Intelligence Framework' from 'Be Your Own Commander-in-Chief'. This structured approach involves interviewing 8-12 professionals in your target field across different: 1) Career stages (early, mid, senior, executive), 2) Organization types (startups, established companies, consulting, non-profit), 3) Specialization areas, and 4) Background transitions (those who've made similar pivots).\n\nPrepare detailed question sets covering: daily responsibilities, skill requirements, industry trends, entry barriers, compensation structures, advancement patterns, and satisfaction drivers. Synthesize findings into a detailed report identifying patterns, contradictions, and hidden requirements. Research shows career changers who conduct structured research have 2.5x higher success rates and 40% shorter transition timelines than those relying on general impressions.",
    
    "Map your transferable skills using the 'Career Capital Inventory' detailed in 'Be Your Own Commander-in-Chief'. This process includes: 1) Comprehensive skills audit across technical, functional, leadership, and adaptive capabilities, 2) Translation mapping to match your terminology with target industry language, 3) Evidence compilation with specific examples demonstrating each skill, and 4) Gap identification compared to ideal candidate profiles.\n\nFocus particularly on universal high-value skills like strategic thinking, stakeholder management, problem-solving methodologies, data analysis, project management, and change leadership. Research from 'Be Your Own Commander-in-Chief' indicates successful career changers typically leverage 60-70% of existing skills while developing 30-40% new capabilities, making skill articulation critical to transition success.",
    
    "Develop practical experience in your new field using the 'Career Transition Portfolio' strategy from 'Be Your Own Commander-in-Chief'. This multi-channel approach includes: 1) Side projects with documented outcomes, 2) Volunteer leadership in relevant organizations, 3) Course projects specifically selected for portfolio building, 4) Open-source or community contributions, and 5) Consulting or freelance work even at reduced rates initially.\n\nCreate a comprehensive digital portfolio showcasing these experiences with problem statements, methodologies, outcomes, and skills demonstrated. According to hiring research, career changers with portfolios of practical work receive interview invitations at 3x the rate of those with courses alone, even when competing against candidates with traditional backgrounds. Aim for 3-5 substantial projects demonstrating core competencies required in your target roles.",
    
    "Craft your career change narrative using the 'Purposeful Pivot Framework' outlined in 'Be Your Own Commander-in-Chief'. This structured approach includes: 1) Articulating a compelling 'why' connecting your past experience to future goals, 2) Demonstrating thoughtful research and deliberate decision-making, 3) Highlighting specific transferable skills with supporting evidence, and 4) Expressing forward-looking enthusiasm rather than dissatisfaction with your current field.\n\nDevelop tailored versions of this narrative for different audiences: networking conversations, application materials, interviews, and social media profiles. Research shows hiring managers are 4x more likely to consider career changers who present coherent transition stories that emphasize continuity of purpose and accumulated advantages rather than completely fresh starts. According to 'Be Your Own Commander-in-Chief', effective career change narratives bridge past achievements and future contributions through transferable capabilities and enduring professional motivations."
  ],
  leadership: [
    "Develop emotional intelligence as a leader using the 'Conscious Leadership Assessment' framework from 'Be Your Own Commander-in-Chief'. This comprehensive approach involves: 1) Self-awareness evaluation using structured feedback tools, 2) Emotion regulation practice through mindfulness techniques, 3) Motivation analysis to understand your leadership drivers, 4) Empathy development through perspective-taking exercises, and 5) Relationship management strategies customized to team dynamics.\n\nResearch from organizational psychology shows leaders with high emotional intelligence create teams with 20-25% higher productivity, 45% lower turnover, and significantly higher innovation rates. According to 'Be Your Own Commander-in-Chief', emotional intelligence capabilities can be systematically developed through deliberate practice rather than being fixed traits, with measurable improvement possible within 6-9 months of focused development.",
    
    "Master delegation using the 'Strategic Empowerment System' detailed in 'Be Your Own Commander-in-Chief'. This four-component framework includes: 1) Task Analysis - mapping assignments to development needs and capabilities, 2) Clear Chartering - defining outcomes, boundaries and authority levels explicitly, 3) Calibrated Support - providing resources and guidance matched to experience level, and 4) Progressive Autonomy - systematically reducing oversight as competence develops.\n\nResearch shows effective delegators create developmental journeys for team members, with tasks growing in complexity and independence over time. According to leadership studies, managers who delegate effectively free up 15-20% of their time for strategic work while simultaneously increasing team capability by 25-30% annually. The key is balancing appropriate challenge with adequate support, with both under-delegation (micromanagement) and over-delegation (abandonment) leading to suboptimal outcomes.",
    
    "Implement the 'Communication Architecture' approach from 'Be Your Own Commander-in-Chief' by creating a comprehensive information sharing system. This includes: 1) Communication Cadence - structured schedule for individual and team interactions, 2) Format Optimization - matching medium to message type, 3) Information Hierarchy - clarifying essential versus optional content, and 4) Feedback Mechanisms - creating psychological safety for upward communication.\n\nResearch indicates teams with established communication frameworks demonstrate 37% higher project success rates and 28% fewer execution delays than those with ad-hoc approaches. According to 'Be Your Own Commander-in-Chief', effective leaders customize communication frequency, detail level, and format based on team member working styles and project phases, creating consistent yet flexible information flows that balance transparency with focus protection.",
    
    "Lead by example using the 'Congruent Leadership Model' outlined in 'Be Your Own Commander-in-Chief'. This approach involves: 1) Values Clarification - explicitly defining and regularly referencing core principles, 2) Behavior Alignment - ensuring your actions visibly demonstrate stated values, 3) Decision Transparency - articulating reasoning processes behind choices, and 4) Accountability Systems - inviting feedback on leadership consistency.\n\nOrganizational research shows leader behavior sets cultural norms more powerfully than formal policies, with teams adopting work ethic, quality standards, collaboration patterns, and ethical guidelines modeled by leaders. According to 'Be Your Own Commander-in-Chief', this modeling effect explains 40-60% of team culture formation, making conscious leadership behavior a critical lever for organizational development. Leaders should regularly audit their 'behavior-value alignment' to identify and address inconsistencies between stated principles and demonstrated actions."
  ],
  general: [
    "Create a personal board of directors using the 'Career Advisory Framework' from 'Be Your Own Commander-in-Chief'. This structured approach involves identifying 5-7 advisors covering distinct domains: 1) Industry Expert with deep sector knowledge, 2) Technical Mentor in your specialty area, 3) Leadership Coach for management development, 4) Financial Advisor for compensation and investment guidance, 5) Entrepreneurial Guide for innovation perspective, 6) Work-Life Integration Counselor, and 7) Career Strategist for long-term planning.\n\nUnlike casual mentoring, formalize these relationships with explicit agreements: meeting frequency, preparation expectations, confidentiality boundaries, and reciprocal value exchange. Research shows professionals with structured advisory boards make major career decisions 35% faster with 52% higher satisfaction rates three years later compared to those relying on informal or singular advice sources.",
    
    "Conduct quarterly career reviews using the 'Strategic Alignment Audit' detailed in 'Be Your Own Commander-in-Chief'. This comprehensive assessment examines: 1) Values-Work Alignment - how daily activities reflect core principles, 2) Skills-Market Demand Match - how capabilities align with emerging opportunities, 3) Compensation-Value Exchange - how rewards reflect contributions, 4) Growth-Goal Progress - advancement toward defined milestones, and 5) Energy-Engagement Balance - sustainability of current demands.\n\nEffective reviews combine quantitative metrics (skills acquired, responsibilities gained, compensation changes) with qualitative reflection (fulfillment, challenge level, relationship quality). According to career development research, professionals who conduct structured quarterly reviews make proactive changes 2-3 years earlier than those who rely on annual reflections or reactive responses to dissatisfaction, resulting in significantly higher lifetime earnings and satisfaction.",
    
    "Build your personal brand through the 'Authentic Expertise Positioning' strategy from 'Be Your Own Commander-in-Chief'. This methodology involves: 1) Domain Definition - identifying your specific expertise intersection, 2) Perspective Development - articulating your unique viewpoint, 3) Content Architecture - creating a systematic knowledge-sharing approach, and 4) Platform Selection - choosing channels aligned with industry norms and personal strengths.\n\nResearch shows consistent thought leadership in a defined specialty area correlates with 32% higher perceived expertise ratings and 48% more senior opportunities compared to general professional networking. According to 'Be Your Own Commander-in-Chief', effective personal branding requires consistency in message and regular engagement rather than sporadic activity, with the compound effect of sustained presence building reputation capital over time.",
    
    "Cultivate a growth mindset using the 'Adaptive Performance System' outlined in 'Be Your Own Commander-in-Chief'. This framework includes: 1) Learning Orientation - viewing challenges as growth opportunities, 2) Failure Analysis - conducting structured reviews of setbacks, 3) Feedback Integration - actively soliciting and applying input, 4) Experimentation Protocols - testing new approaches systematically, and 5) Progress Measurement - tracking development over time.\n\nNeuropsychological research confirms that growth mindset can be deliberately developed through specific practices rather than being an innate trait. According to studies cited in 'Be Your Own Commander-in-Chief', professionals who adopt structured growth mindset practices show 41% higher rates of skill acquisition, 37% greater leadership effectiveness scores, and 29% more innovation contributions than fixed-mindset peers with similar experience and capabilities."
  ],
  salary_data: [
    "When researching compensation, triangulate data from multiple specialized sources beyond general sites. For tech roles, Levels.fyi provides detailed breakdowns by level, company, and location. For executive positions, the ExecComp database offers comprehensive information on total packages including equity and benefits. Industry association salary surveys often provide the most accurate niche data - for example, the IEEE Salary Survey for engineering roles or SaaS Capital Reports for software leadership positions.\n\nAccording to 'Be Your Own Commander-in-Chief', create comparison matrices across similar roles, calculating your specific 'premium percentage' based on specialized skills, revenue impact history, and unique experience combinations. Research shows professionals who present compensation discussions with multi-source data receive offers 12-18% higher than those using single-source references.",
    
    "When analyzing your market value, incorporate the 'Total Compensation Calculator' methodology from 'Be Your Own Commander-in-Chief'. This involves quantifying: 1) Base Compensation, 2) Performance Bonuses, 3) Equity Value (with appropriate discount rates), 4) Benefits Package, 5) Retirement Contributions, 6) Learning & Development Allowances, 7) Flexibility Premium (monetary value of remote/flexible arrangements), and 8) Advancement Trajectory (expected compensation growth).\n\nSpecifically for your industry, recent data shows that roles with similar responsibilities have seen 7-12% increases over the past year, with particular premiums for expertise in [relevant technologies/skills]. Companies like [specific competitors] are offering packages 15-20% above market to attract top talent with your profile."
  ],
  linkedin_optimization: [
    "Optimize your LinkedIn profile using the 'Social Proof Architecture' framework from 'Be Your Own Commander-in-Chief'. This comprehensive approach involves: 1) Strategic Keyword Placement in your headline, about section, and experience descriptions based on recruiter search patterns, 2) Accomplishment Storytelling with specific metrics and outcomes for each role, 3) Social Validation through strategically requested recommendations that highlight specific capabilities, 4) Portfolio Integration with project showcases and media attachments, and 5) Engagement Engineering through thoughtful content creation and curation.\n\nData from LinkedIn optimization studies shows profiles with industry-specific keywords in prime positions receive 30-40% more recruiter views. According to 'Be Your Own Commander-in-Chief', headlines that combine current role, expertise area, and value proposition generate 45% higher engagement than standard job title formats.",
    
    "Create a compelling LinkedIn headline using the 'Value Proposition Formula' detailed in 'Be Your Own Commander-in-Chief': [Current Role] + [Expertise Domain] + [Outcome Delivered] + [Key Credential]. For example: 'Marketing Director | Customer Acquisition Strategist | Driving 40%+ Growth for SaaS | HBS Alum'.\n\nYour LinkedIn About section should follow the 'Career Narrative Structure': opening hook highlighting key achievement, professional mission statement, 3-4 areas of expertise with evidence, unique professional perspective, and clear call to action. Research shows profiles with structured About sections following this format receive 71% more profile views and 35% more connection requests than unstructured summaries of similar length.",
    
    "Enhance your LinkedIn visibility using the 'Strategic Engagement System' from 'Be Your Own Commander-in-Chief'. This data-driven approach involves: 1) Content Calendar - planning regular posting schedule aligned with LinkedIn's algorithm preferences (currently favoring text posts with 1300-1700 characters without external links), 2) Engagement Groups - participating in 3-5 relevant professional communities with consistent activity, 3) Comment Strategy - providing substantive insights on influencer content for visibility expansion, and 4) Original Content Development focused on your specific expertise areas.\n\nLinkedIn analytics shows professional profiles with weekly activity appearing in 4x more search results than dormant profiles with identical qualifications. According to 'Be Your Own Commander-in-Chief', the most effective engagement pattern involves 2-3 original posts weekly, 5-7 substantive comments on high-traffic content, and selective content sharing with added perspective rather than simple re-sharing."
  ],
  document_analysis: [
    "I've analyzed your uploaded resume and notice several opportunities for improvement based on 'Be Your Own Commander-in-Chief' principles: 1) Your experience section uses general responsibility statements rather than achievement-focused bullets with metrics. Research shows resumes with quantified achievements receive 40% more interview invitations. 2) Your skills section lists technologies without proficiency levels or application contexts, missing opportunities to demonstrate depth. 3) Your career progression doesn't highlight increasing responsibility or scope expansion clearly.\n\nConsider restructuring using the 'Achievement Formula': Challenge faced + Action taken + Result achieved + Significance to business. For example, instead of 'Responsible for marketing campaigns,' write 'Developed integrated marketing strategy for struggling product line, increasing quarterly sales by 32% ($1.2M) and recapturing market share from key competitor.'"
  ]
};

// Categories for keyword matching
export const categories: Record<string, string[]> = {
  interviews: ["interview", "hiring", "questions", "recruiter", "preparation", "behavioral questions", "technical interview", "case study interview", "phone screen", "onsite interview", "panel interview"],
  
  salary: ["salary", "compensation", "negotiate", "pay", "raise", "money", "benefits", "bonus", "equity", "stock options", "total comp", "offer", "counter offer", "merit increase", "promotion raise", "market rate", "salary band"],
  
  promotion: ["promotion", "advance", "career path", "growth", "next level", "senior", "title", "responsibilities", "career progression", "advancement", "upward mobility", "leveling up", "promotion criteria", "performance review", "manager promotion"],
  
  skills: ["skills", "learn", "training", "develop", "expertise", "knowledge", "competencies", "upskill", "reskill", "certification", "course", "learning path", "technical skills", "soft skills", "skill gap", "transferable skills"],
  
  networking: ["network", "connection", "contact", "relationship", "linkedin", "professional network", "referral", "introduction", "networking event", "conference", "professional association", "alumni network", "mentorship", "industry connection"],
  
  career_change: ["change", "transition", "pivot", "switch", "new field", "different role", "career shift", "industry change", "new industry", "reinvention", "career reset", "different path", "new direction", "career transition", "pivot strategy"],
  
  leadership: ["leader", "manage", "team", "supervise", "executive", "director", "leadership style", "management technique", "people management", "team building", "executive presence", "delegation", "coaching staff", "performance management", "leadership development"],
  
  general: ["career", "job", "work", "professional", "advice", "strategy", "planning", "future", "goals", "objective", "purpose", "vision", "mission", "satisfaction", "fulfillment", "work-life balance"],
  
  salary_data: ["average salary", "pay scale", "compensation data", "salary report", "industry average", "salary range", "market rate", "compensation benchmark", "salary survey", "pay data", "competitive salary", "compensation trends", "salary statistics"],
  
  linkedin_optimization: ["linkedin profile", "linkedin summary", "linkedin headline", "endorsements", "recommendations", "linkedin visibility", "profile views", "linkedin algorithm", "linkedin content", "linkedin engagement", "linkedin network", "profile optimization", "linkedin photo", "linkedin about section"],
  
  document_analysis: ["resume", "cv", "cover letter", "portfolio", "work samples", "professional documents", "application materials", "resume format", "resume review", "document feedback", "resume gaps", "resume achievements", "resume bullets", "resume summary"]
};

